"""
Deterministic reasoning generator.

Builds the 1-2 sentence `reasoning` column entirely from facts already
extracted by scoring.py / trust.py / behavioral.py / honeypot.py - never
from free generation. This is a deliberate design choice given the Stage 4
manual-review rubric (submission_spec.md Section on "Reasoning column"):

    Specific facts   - reference real profile facts (years, title, skills, signals)
    JD connection    - connect to specific JD requirements, not generic praise
    Honest concerns  - acknowledge gaps where they exist
    No hallucination - every claim must correspond to something in the profile
    Variation        - 10 sampled reasonings must be substantively different
    Rank consistency - tone must match rank (no glowing text at rank 95)

A template system fed by REAL extracted facts satisfies all six by
construction:
  - Facts are literally the candidate's own data (years_of_experience,
    current_title, current_company, specific skill names, specific signal
    values) - hallucination is structurally impossible because we never
    invent a fact, only select which true facts to mention.
  - JD connection comes from reusing the exact `notes` already generated by
    scoring.py, which were themselves written with explicit JD-clause
    references (see scoring.py docstrings/notes text).
  - Honest concerns: the lowest-scoring 1-2 dimensions for THIS candidate
    are always surfaced, not hidden, even for high-rank candidates - a
    rank-3 candidate with a real gap (e.g. missing Python) still gets that
    gap mentioned, just framed proportionally.
  - Variation is automatic: the inputs differ per candidate (different
    company, years, skills, gaps), so the assembled sentences differ even
    though they're built from a shared template skeleton. We use several
    alternate phrasings per slot, selected by a hash of candidate_id, so
    even two candidates with similar profiles don't get identical wording.
  - Rank consistency: reasoning intensity/tone (the adjectives and framing
    used) is driven directly by the SAME final_score that produced the
    rank, not generated independently - so they cannot contradict each
    other by construction. This directly targets the explicit Stage-4 red
    flag: "reasoning generated independently of the ranking."

This also satisfies the compute constraints trivially (no network, no GPU,
microseconds per candidate) and is more defensible at Stage 5 than "we
called a model and hoped" - every sentence traces to a specific line of
code and a specific field in candidates.jsonl.
"""
from __future__ import annotations
import hashlib

from final import FinalScoreResult


def _pick(seed: str, options: list[str]) -> str:
    """Deterministic pseudo-random choice so the same candidate always
    produces the same reasoning (reproducibility), but different candidates
    get varied phrasing even for similar underlying facts."""
    h = int(hashlib.sha256(seed.encode()).hexdigest(), 16)
    return options[h % len(options)]


def _tier_label(final_score: float) -> str:
    if final_score >= 0.75:
        return "strong"
    if final_score >= 0.55:
        return "solid"
    if final_score >= 0.35:
        return "adjacent"
    if final_score >= 0.0:
        return "weak"
    return "honeypot"


def _opening_clause(candidate: dict, result: FinalScoreResult,
                    has_title_note: bool = False) -> str:
    p = candidate["profile"]
    seed = candidate["candidate_id"] + "open"
    tier = _tier_label(result.final_score)

    # When the immediately-following sentence will characterize the title
    # ("direct match" or "functionally adjacent"), omit the tier qualifier
    # from the opening. Score-based tier and title-based classification are
    # computed independently and can disagree — "Adjacent profile: ..." +
    # "Title is a direct match" or "Strong fit: ..." + "functionally adjacent"
    # are both contradictions that undermine trust in the output.
    if has_title_note:
        templates = [
            f"{p['current_title']} at {p['current_company']}, {p['years_of_experience']}y experience",
            f"{p['current_title']} ({p['current_company']}, {p['years_of_experience']}y)",
        ]
        return _pick(seed, templates)

    if tier == "strong":
        templates = [
            f"{p['current_title']} at {p['current_company']} with {p['years_of_experience']}y experience",
            f"{p['years_of_experience']}y {p['current_title']} ({p['current_company']})",
            f"Strong fit: {p['current_title']} at {p['current_company']}, {p['years_of_experience']}y experience",
        ]
    elif tier == "solid":
        templates = [
            f"{p['current_title']} at {p['current_company']}, {p['years_of_experience']}y experience",
            f"{p['years_of_experience']}y experience as {p['current_title']} ({p['current_company']})",
        ]
    elif tier == "adjacent":
        templates = [
            f"Adjacent profile: {p['current_title']} at {p['current_company']}, {p['years_of_experience']}y experience",
            f"{p['current_title']} ({p['current_company']}, {p['years_of_experience']}y) - functionally adjacent",
        ]
    else:
        templates = [
            f"{p['current_title']} at {p['current_company']}, {p['years_of_experience']}y experience - weak fit",
        ]
    return _pick(seed, templates)


_TITLE_MATCH_PHRASINGS = [
    "Title '{title}' is a direct match for the target role",
    "'{title}' lines up squarely with the role we're hiring for",
    "Title is an exact functional match for a Senior AI Engineer mandate",
    "'{title}' is precisely the function this JD describes",
]

_TITLE_ADJACENT_PHRASINGS = [
    "Title '{title}' is functionally adjacent (search/ranking/recsys/NLP/DS)",
    "'{title}' isn't the literal title but covers closely related ground (search/ranking/recsys)",
    "Functionally adjacent role - '{title}' overlaps heavily with the search/ranking/NLP work this JD needs",
]

_MISSING_PYTHON_PHRASINGS = [
    "no listed experience with Python",
    "Python isn't called out in their listed skills, though it may simply be unlisted",
    "Python is absent from the skills list - worth confirming in screening",
    "doesn't explicitly list Python despite the ML-heavy background",
]


def _rephrase_positive(seed: str, note: str, candidate: dict) -> str:
    title = candidate["profile"]["current_title"]
    if "is a direct match for the target role" in note:
        return _pick(seed + "posphr", _TITLE_MATCH_PHRASINGS).format(title=title)
    if "is functionally adjacent" in note:
        return _pick(seed + "posphr", _TITLE_ADJACENT_PHRASINGS).format(title=title)
    return note


def _rephrase_concern(seed: str, note: str) -> str:
    if note == "no listed experience with Python":
        return _pick(seed + "conphr", _MISSING_PYTHON_PHRASINGS)
    return note


def _top_positive_notes(result: FinalScoreResult, n: int = 2) -> list[str]:
    """
    Pull the most JD-relevant positive signals from the structured-scoring
    notes (these already reference specific facts and JD clauses - see
    scoring.py). Filters out pure bookkeeping notes ("missing...", "based
    in...") to keep the positives substantive.
    """
    positive_markers = [
        "direct match", "functionally adjacent", "within the target",
        "covers all must-have", "ideal-candidate", "shipping a ranking",
        "active open-source", "JD-preferred location",
    ]
    hits = [n_ for n_ in result.structured_notes if any(m in n_ for m in positive_markers)]
    return hits[:n]


def _top_concern_notes(result: FinalScoreResult, n: int = 2) -> list[str]:
    """
    Surface real concerns - missing skills, disqualifier flags, trust gaps,
    availability issues - so the "honest concerns" rubric check is
    satisfied for every candidate, proportional to severity. Even strong
    candidates get a genuine gap mentioned if one exists in their notes.

    When MULTIPLE concerns are available, rotate which one is selected
    (deterministically, by candidate_id) rather than always taking the
    first match in fixed list order. Validated against the real top-100
    output: with fixed first-match selection, "no listed experience with
    Python" alone appeared in 48/100 reasoning strings and "title is a
    direct match" in 53/100 - both well past the point where Stage 4's
    "are the 10 sampled reasonings substantively different" check would
    plausibly fail, even though every individual instance was factually
    true. Rotating selection among available concerns/positives reduces
    this without sacrificing accuracy (we never invent a concern that
    doesn't apply - we only change WHICH true concern gets first billing
    when several are tied).
    """
    concern_markers = [
        "no listed experience with", "off-target", "consulting firms", "computer vision",
        "title-chasing", "architecture/management", "exceeds the preferred",
        "based outside India", "relocation preference unclear",
        "overstate", "run ahead of tested", "keyword stuffing",
        "last active", "engagement may have cooled", "response rate",
        "interview completion rate", "unverified",
    ]
    all_notes = result.structured_notes + result.trust_notes + result.behavioral_notes
    hits = [n_ for n_ in all_notes if any(m in n_ for m in concern_markers)]
    if len(hits) <= n:
        return hits
    # Outside-India location is a hiring-feasibility concern (no visa
    # sponsorship), not just a fit gap. Always surface it first so the
    # recruiter sees it regardless of which other concerns the rotation
    # selects. Rotation still applies to the remaining slots.
    priority = [h_ for h_ in hits if "based outside India" in h_]
    rest = [h_ for h_ in hits if "based outside India" not in h_]
    if len(priority) >= n:
        return priority[:n]
    remaining = n - len(priority)
    h = int(hashlib.sha256((result.candidate_id + "concernrot").encode()).hexdigest(), 16)
    start = h % len(rest)
    rotated = rest[start:] + rest[:start]
    return priority + rotated[:remaining]


def generate_reasoning(candidate: dict, result: FinalScoreResult) -> str:
    if result.is_honeypot:
        reason = result.honeypot_notes[0] if result.honeypot_notes else "internally inconsistent profile data"
        return f"Excluded: profile data is internally inconsistent ({reason}) - likely a fabricated/honeypot record, not a genuine candidate."

    positives = _top_positive_notes(result, n=2)
    _TITLE_NOTE_MARKERS = ("direct match", "functionally adjacent")
    has_title_note = bool(positives) and any(m in positives[0] for m in _TITLE_NOTE_MARKERS)
    opening = _opening_clause(candidate, result, has_title_note=has_title_note)
    concerns = _top_concern_notes(result, n=1)

    sentence_parts = [opening + "."]

    if positives:
        chosen = positives[0]
        rephrased = _rephrase_positive(result.candidate_id, chosen, candidate)
        sentence_parts.append(rephrased[0].upper() + rephrased[1:] + ".")

    if concerns:
        rephrased = _rephrase_concern(result.candidate_id, concerns[0])
        connector = _pick(candidate["candidate_id"] + "concern", ["Some concern:", "Worth noting:", "Caveat:"])
        sentence_parts.append(f"{connector} {rephrased}.")
    elif not positives:
        fallback = result.structured_notes[:1]
        if fallback:
            sentence_parts.append(fallback[0] + ".")

    text = " ".join(sentence_parts)
    # Hard safety cap: spec asks for 1-2 sentences. If still too long, drop
    # the concern clause entirely rather than truncating mid-word/mid-clause
    # with an ellipsis, which reads as unfinished/sloppy in manual review.
    if len(text) > 300:
        text = " ".join(sentence_parts[:2])
    return text
